//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileKeeperMAUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileKeeperMAUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;
        ///    &lt;Modulus&gt;52hZyxjs+yFj4SckiITIoTlMFl8fj0O54mqIPsvgNBFhulqBNd1+rlEQeHxXaev3MHCRD+i3Rc0roQaGJaDuUbcCicZiqlnwD/QPV8YT0gNmapaWDGm0btZzdf2Pp5ZpHD8LgnAxKEvz3tRRw4/3ntXjJlZ8e7gQg491D/N5PwE=&lt;/Modulus&gt;
        ///    &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///    &lt;P&gt;+Ang+TGYPZV+57hiQWSmeWgXe8O6bGo1HcS3mSbhgzSQOXau9aTXHU7yzsZJ7yioiuKejLwtga48y9Mzjqw7ew==&lt;/P&gt;
        ///    &lt;Q&gt;7tXQ6oGxndizTTivxmUdCYhCcY3thv4QhkVbYblO9u1Aa05jjyZV9fthIja/3/Hh18p4/f+ytgd93cTkel54sw==&lt;/Q&gt;
        ///    &lt;DP&gt;iMG5nuuvStUwQUayNefuuaWgvQZvtPLiEmWx7Ok5EYRbuLMtSBb43Bn5WfS [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Rfile {
            get {
                return ResourceManager.GetString("Rfile", resourceCulture);
            }
        }
    }
}
